import {
  UserOutlined,
  HomeOutlined,
  CloudUploadOutlined,
  RobotOutlined,
  FileSearchOutlined,
  ThunderboltOutlined,
  UsergroupDeleteOutlined,
  NodeIndexOutlined,
  AuditOutlined,
  BellOutlined,
  BranchesOutlined,
  SendOutlined,
  RocketOutlined,
  DisconnectOutlined,
  GlobalOutlined,
  EditOutlined,
  SnippetsOutlined,
} from '@ant-design/icons'

export const SideMenuList = {
  首页: <HomeOutlined />,
  用户管理: <UserOutlined />,
  权限管理: <ThunderboltOutlined />,
  新闻管理: <FileSearchOutlined />,
  审核管理: <RobotOutlined />,
  发布管理: <CloudUploadOutlined />,
  用户列表: <UsergroupDeleteOutlined />,
  角色列表: <NodeIndexOutlined />,
  权限列表: <GlobalOutlined />,
  撰写新闻: <EditOutlined />,
  草稿箱: <SnippetsOutlined />,
  新闻分类: <AuditOutlined />,
  审核新闻: <BellOutlined />,
  审核列表: <BranchesOutlined />,
  待发布: <SendOutlined />,
  已发布: <RocketOutlined />,
  已下线: <DisconnectOutlined />,
}
