import {
  UserOutlined,
  HomeOutlined,
  CloudUploadOutlined,
  RobotOutlined,
  FileSearchOutlined,
  ThunderboltOutlined,
  UsergroupDeleteOutlined,
  NodeIndexOutlined,
  AuditOutlined,
  BellOutlined,
  BranchesOutlined,
  SendOutlined,
  RocketOutlined,
  DisconnectOutlined,
  GlobalOutlined,
  EditOutlined,
  SnippetsOutlined,
  ApartmentOutlined,
  UngroupOutlined,
  UnorderedListOutlined,
} from '@ant-design/icons'

export const SideMenuIcon = {
  首页: <HomeOutlined />,
  用户管理: <UserOutlined />,
  新闻管理: <FileSearchOutlined />,
  发布新闻: <CloudUploadOutlined />,
  志愿活动管理: <ThunderboltOutlined />,
  发布志愿活动: <RobotOutlined />,
  志愿者信息: <UsergroupDeleteOutlined />,
  咨询管理: <NodeIndexOutlined />,
  咨询回复: <GlobalOutlined />,
  普法动态管理: <EditOutlined />,
  家政商家管理: <SnippetsOutlined />,
  商家标签管理: <AuditOutlined />,
  医院管理: <BellOutlined />,
  预约管理: <BranchesOutlined />,
  诊所管理: <SendOutlined />,
  健康资讯管理: <RocketOutlined />,
  健康资讯发布: <DisconnectOutlined />,
  论坛分类: <ApartmentOutlined />,
  论坛审核: <UngroupOutlined />,
  论坛列表: <UnorderedListOutlined />,
}
